2020-03-19 05:03:12.579774: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda-10.0/lib:/usr/local/cuda-10.0/efa/lib:/opt/amazon/efa/lib:/opt/amazon/efa/lib64:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/::/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow
2020-03-19 05:03:12.579874: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:/usr/local/cuda-10.0/lib:/usr/local/cuda-10.0/efa/lib:/opt/amazon/efa/lib:/opt/amazon/efa/lib64:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/::/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow
2020-03-19 05:03:12.579884: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-03-19 05:03:13.068881: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-03-19 05:03:13.080383: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-03-19 05:03:13.080425: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-10-10-13-145): /proc/driver/nvidia/version does not exist
2020-03-19 05:03:13.081494: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-03-19 05:03:13.108349: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2020-03-19 05:03:13.109062: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55793dacb180 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-19 05:03:13.109081: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-03-19 05:03:13.111308: I tensorflow/core/common_runtime/direct_session.cc:358] Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device

WARNING:tensorflow:From SlidingWindow-RNN_Fraud_Detection.py:109: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.9min remaining:    0.0s
Traceback (most recent call last):
  File "SlidingWindow-RNN_Fraud_Detection.py", line 1392, in <module>
    history = rnn.train( X_train, y_train, X_test, y_test )
  File "SlidingWindow-RNN_Fraud_Detection.py", line 1175, in train
    callbacks      = self.callbacks   
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/parallel.py", line 1007, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 209, in apply_async
    result = ImmediateResult(func)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 590, in __init__
    self.results = batch()
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 508, in _fit_and_score
    X_train, y_train = _safe_split(estimator, X, y, train)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 201, in _safe_split
    X_subset = _safe_indexing(X, indices)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 413, in _safe_indexing
    return _array_indexing(X, indices, indices_dtype, axis=axis)
  File "/home/ec2-user/anaconda3/envs/verafin-mitacs-2020/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 199, in _array_indexing
    return array[key] if axis == 0 else array[:, key]
MemoryError
